spring:
  h2:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
      