spring:
  mysql:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qms
    username: root 
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
      